In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.callbacks import TensorBoard

In [19]:
list = [["hellokhfhttdhrsytduiuguug" , "how", "are", "you"]]
arr1 = np.array(list)
arr1.dtype

dtype('<U25')

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.ones(11)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.empty((3,4,5)).shape

(3, 4, 5)

In [15]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
arr = np.array([1,2,3,4,5,6])
arr.dtype

dtype('int32')

In [21]:
float_arr = arr.astype(np.float64)

In [22]:
float_arr

array([1., 2., 3., 4., 5., 6.])

In [26]:
numeric_string = np.array(['1.25','2.5','3'])
numeric = numeric_string.astype(np.int16)
numeric

ValueError: invalid literal for int() with base 10: '1.25'

In [27]:
arr = np.arange(20)

In [31]:
arr[5:9] = 7
arr

array([ 0,  1,  2,  3,  4,  7,  7,  7,  7,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [33]:
arr[:] = 22
arr

array([22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
       22, 22, 22])

In [34]:
arr = np.identity(7)

In [35]:
arr[2,2]

1.0

In [2]:
a = np.ones((12288, 150))
b = np.ones((150, 45))

In [3]:
c = np.dot(a,b)
c.shape

(12288, 45)

In [4]:
c

array([[150., 150., 150., ..., 150., 150., 150.],
       [150., 150., 150., ..., 150., 150., 150.],
       [150., 150., 150., ..., 150., 150., 150.],
       ...,
       [150., 150., 150., ..., 150., 150., 150.],
       [150., 150., 150., ..., 150., 150., 150.],
       [150., 150., 150., ..., 150., 150., 150.]])

In [5]:
!pip install h5py

In [6]:
!pip instal

In [2]:
import pandas as pd
df = pd.read_hdf('train_catvnoncat.h5')
df

ValueError: Dataset(s) incompatible with Pandas data types, not table, or no datasets found in HDF5 file.

In [3]:
X = []
y = []
w = []
b = []

In [3]:
z = np.dot(X,w.T) + b
a = sigmoid(z)


NameError: name 'X' is not defined

In [16]:
names = np.array(['Sadik','Mahamud','Shakshor','Sadik','Shawrin','Mahi',
                 'Mou','Mon','Jahanara','Shirin'])
names

array(['Sadik', 'Mahamud', 'Shakshor', 'Sadik', 'Shawrin', 'Mahi', 'Mou',
       'Mon', 'Jahanara', 'Shirin'], dtype='<U8')

In [17]:
data = np.random.rand(10,4)
data

array([[0.6699338 , 0.32577222, 0.98444474, 0.9659373 ],
       [0.94384564, 0.33131126, 0.1310696 , 0.18336168],
       [0.75833824, 0.17575346, 0.44451917, 0.99425469],
       [0.58883622, 0.98850119, 0.66762527, 0.97125785],
       [0.90716015, 0.91205314, 0.60487978, 0.53685978],
       [0.43139936, 0.44899965, 0.15863963, 0.27079827],
       [0.96415479, 0.20317931, 0.37635475, 0.34302026],
       [0.59199507, 0.87492957, 0.66418508, 0.31116841],
       [0.59731432, 0.38277908, 0.06584998, 0.40816636],
       [0.75689646, 0.12207856, 0.53103616, 0.82640611]])

In [18]:
names == 'Sadik'

array([ True, False, False,  True, False, False, False, False, False,
       False])

In [19]:
data[names == 'Sadik']

array([[0.6699338 , 0.32577222, 0.98444474, 0.9659373 ],
       [0.58883622, 0.98850119, 0.66762527, 0.97125785]])

In [24]:
mask = (names == 'Sadik') | (names == 'Mahamud')

In [25]:
data[mask]

array([[0.6699338 , 0.32577222, 0.98444474, 0.9659373 ],
       [0.94384564, 0.33131126, 0.1310696 , 0.18336168],
       [0.58883622, 0.98850119, 0.66762527, 0.97125785]])

In [26]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [28]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [29]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [31]:
arr[[1,4,3,5],[2,0,1,3]]

array([ 6, 16, 13, 23])

In [32]:
arr = np.random.randn(8)

In [33]:
arr

array([-1.04907241, -0.92155507,  0.87061165,  0.34044276,  0.55143805,
        0.7787767 ,  0.55692178, -2.05991705])

In [35]:
np.sign(arr)

array([-1., -1.,  1.,  1.,  1.,  1.,  1., -1.])

In [43]:
xs, ys = np.meshgrid(points, points)

In [44]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [40]:
points = [1,2,3,4]
xs , ys = np.meshgrid(points, points)
ys

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

In [45]:
arr = np.random.randn(35).reshape(7,5)

In [47]:
np.where(arr>1, 1, arr)

array([[-0.09260997, -0.58491506,  0.53051447,  1.        ,  1.        ],
       [ 0.05014728,  1.        ,  1.        , -0.78945182,  1.        ],
       [-0.05238622,  1.        , -0.53307172, -0.65118568, -0.66289197],
       [-1.52534956, -0.96194825, -1.92940548,  1.        , -1.75578816],
       [-0.95145667,  0.03201262, -0.55532859,  0.25395393, -0.41956786],
       [ 1.        ,  1.        ,  0.04477301, -1.24995568,  0.08935274],
       [-0.92630993, -2.44249668,  0.69665837, -0.02307514, -0.78570897]])

In [48]:
arr = np.random.randn(5,4)
arr

array([[ 0.32084635,  0.71926456,  1.34734284,  0.02538398],
       [-0.16328385, -1.41380789, -0.41778602,  1.5293642 ],
       [-2.15209069, -0.38260837, -0.70056004,  1.59890258],
       [-0.89360035, -0.59275726, -0.87906249,  0.63187269],
       [ 0.74732951, -0.97175475, -1.87030666, -0.83456026]])

In [49]:
np.mean(arr)

-0.21759359720996657

In [50]:
np.sum(arr)

-4.351871944199331

In [51]:
np.mean(arr, axis = 1)

array([ 0.60320943, -0.11637839, -0.40908913, -0.43338685, -0.73232304])

In [52]:
np.sum(arr, axis = 1)

array([ 2.41283774, -0.46551357, -1.63635653, -1.73354741, -2.92929217])

In [53]:
np.std(arr)

1.0457709231491539

In [54]:
np.var(arr)

1.0936368237042333

In [55]:
np.min(arr)

-2.1520906947385225

In [56]:
np.max(arr, axis = 0)

array([0.74732951, 0.71926456, 1.34734284, 1.59890258])

In [57]:
np.argmin(arr)

8

In [59]:
arr = np.random.randn(100)

In [60]:
(arr > 2).sum()

2

In [63]:
x = np.array([1,2,3,4])
y = np.array((3,4,5,6))
np.union1d(x,y)

array([1, 2, 3, 4, 5, 6])

In [2]:
from keras.datasets import mnist

(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [3]:
y_train_bool = (y_train < 5)
y = y_train[y_train_bool]
X = X_train[y_train_bool]
y_test_bool = (y_test < 5)
X_test = X_test[y_test_bool]
y_test = y_test[y_test_bool]

In [4]:
limit = int(X.shape[0]*0.9)
X_train = X[0:limit]
y_train = y[0:limit]
X_val = X[limit:]
y_val = y[limit:]

In [5]:
plt.imshow(x[90], cmap='gray')
plt.show()

# Print the corresponding label
print(y[90])

NameError: name 'x' is not defined

In [6]:
X_train[0].shape

(28, 28)

In [7]:
model = keras.models.Sequential([
    keras.layers.Input((28,28)),
    keras.layers.Flatten(),
    keras.layers.Dense(100, activation = 'elu', kernel_initializer='he_normal'),
    keras.layers.Dense(100, activation = 'elu', kernel_initializer='he_normal'),
    keras.layers.Dense(100, activation = 'elu', kernel_initializer='he_normal'),
    keras.layers.Dense(100, activation = 'elu', kernel_initializer='he_normal'),
    keras.layers.Dense(100, activation = 'elu', kernel_initializer='he_normal'),
    keras.layers.Dense(5, activation = 'softmax')
])

In [8]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ flatten (Flatten)                    │ (None, 784)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 100)                 │          78,500 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 100)                 │          10,100 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 100)                 │          10,100 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 100)                 │          10,100 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 100)                 │          10,100 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 5)                   │             505 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 119,405 (466.43 KB)

 Trainable params: 119,405 (466.43 KB)

 Non-trainable params: 0 (0.00 B)

In [9]:
model.compile(optimizer = "adam", loss = "sparse_categorical_crossentropy", metrics = ['accuracy'])

In [10]:
early_stop = EarlyStopping(monitor = 'val_loss', patience=5,restore_best_weights=True)

In [11]:
model.fit(X_train, y_train, epochs = 100, validation_data = (X_val, y_val), callbacks = [early_stop])

Epoch 1/100
861/861 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8865 - loss: 4.4591 - val_accuracy: 0.9716 - val_loss: 0.1865
Epoch 2/100
861/861 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9656 - loss: 0.2592 - val_accuracy: 0.9703 - val_loss: 0.2083
Epoch 3/100
861/861 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9764 - loss: 0.1208 - val_accuracy: 0.9817 - val_loss: 0.1019
Epoch 4/100
861/861 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9809 - loss: 0.0878 - val_accuracy: 0.9830 - val_loss: 0.0838
Epoch 5/100
861/861 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9817 - loss: 0.0753 - val_accuracy: 0.9856 - val_loss: 0.0729
Epoch 6/100
861/861 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9859 - loss: 0.0527 - val_accuracy: 0.9742 - val_loss: 0.0923
Epoch 7/100
861/861 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9852 - loss: 0.0575 - val_accuracy: 0.9807 - val_loss: 0.0754
Epoch 8/100
861/861 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9852 - loss: 0.0552 - val_accu

In [12]:
y_predict = model.predict(X_test)
y_predict = np.argmax(y_predict,axis = 1)
y_predict

161/161 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


array([2, 1, 0, ..., 2, 3, 4], dtype=int64)

In [13]:
from sklearn.metrics import mean_squared_error

In [14]:
error = np.sqrt(mean_squared_error(y_test, y_predict))

In [15]:
error

0.18818993192183914

In [16]:
model.save('experiment1.keras')

In [17]:
model_A = keras.models.load_model('experiment1.keras')
model_A_clone = keras.models.clone_model(model_A)
model_A_clone.set_weights(model_A.get_weights())

In [18]:
model_B = keras.models.Sequential([
    keras.layers.Input((28,28)),
])
for layer in model_A_clone.layers[1:-1]:
    layer.activation = keras.activations.elu
    layer.kernel_initializer = 'he_normal'
for layer in model_A_clone.layers[:-1]:
    model_B.add(layer)
    model_B.add(keras.layers.BatchNormalization())
model_B.add(keras.layers.Dense(5, activation="softmax"))

In [19]:
for layer in model_B.layers[:-1]:
    layer.trainable = False

In [20]:
model_B.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ flatten (Flatten)                    │ (None, 784)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization                  │ (None, 784)                 │           3,136 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 100)                 │          78,500 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_1                │ (None, 100)                 │             400 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 100)                 │          10,100 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_2                │ (None, 100)                 │             400 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 100)                 │          10,100 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_3                │ (None, 100)                 │             400 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 100)                 │          10,100 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_4                │ (None, 100)                 │             400 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 100)                 │          10,100 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_5                │ (None, 100)                 │             400 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_6 (Dense)                      │ (None, 5)                   │             505 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 124,541 (486.49 KB)

 Trainable params: 505 (1.97 KB)

 Non-trainable params: 124,036 (484.52 KB)

In [21]:
from keras.datasets import mnist
import time

(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [22]:
y_train_bool = (y_train > 4)
x = X_train[y_train_bool]
y = y_train[y_train_bool]
y = y - 5
y_test_bool = (y_test > 4)
y_test = y_test[y_test_bool]
y_test = y_test - 5
X_test = X_test[y_test_bool]
limit = int(x.shape[0]*0.9)
X_train = x[0:limit]
y_train = y[0:limit]
X_val = x[limit:]
y_val = y[limit:]

In [23]:
y_train

array([0, 4, 0, ..., 4, 4, 3], dtype=uint8)

In [24]:
model_B.compile(optimizer='adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])

In [25]:
history = model_B.fit(X_train, y_train, epochs = 5, validation_data = (X_val, y_val))

Epoch 1/5
827/827 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.4016 - loss: 3.5498 - val_accuracy: 0.6651 - val_loss: 0.9764
Epoch 2/5
827/827 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6554 - loss: 1.0026 - val_accuracy: 0.7120 - val_loss: 0.8292
Epoch 3/5
827/827 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6925 - loss: 0.8747 - val_accuracy: 0.7208 - val_loss: 0.8005
Epoch 4/5
827/827 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6987 - loss: 0.8508 - val_accuracy: 0.7198 - val_loss: 0.7831
Epoch 5/5
827/827 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6973 - loss: 0.8394 - val_accuracy: 0.7100 - val_loss: 0.8345


In [214]:
for layer in model_B.layers[:-1]:
    layer.trainable = True

In [215]:
model_B.compile(optimizer='adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])

In [33]:
early_stopping = EarlyStopping(monitor = "val_loss",patience = 5, restore_best_weights= True)

In [31]:
history = model_B.fit(X_train, y_train, epochs = 16, validation_data = (X_val, y_val),callbacks = [early_stopping])

Epoch 1/16
827/827 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8874 - loss: 0.3450 - val_accuracy: 0.9701 - val_loss: 0.1052
Epoch 2/16
827/827 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9717 - loss: 0.0952 - val_accuracy: 0.9796 - val_loss: 0.0693
Epoch 3/16
827/827 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9808 - loss: 0.0697 - val_accuracy: 0.9820 - val_loss: 0.0684
Epoch 4/16
827/827 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9852 - loss: 0.0463 - val_accuracy: 0.9830 - val_loss: 0.0699
Epoch 5/16
827/827 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9865 - loss: 0.0447 - val_accuracy: 0.9847 - val_loss: 0.0627
Epoch 6/16
827/827 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9871 - loss: 0.0452 - val_accuracy: 0.9861 - val_loss: 0.0569
Epoch 7/16
827/827 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9904 - loss: 0.0326 - val_accuracy: 0.9830 - val_loss: 0.0682
Epoch 8/16
827/827 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9893 - loss: 0.0369 - val_accuracy: 0.

In [34]:
y_predict = model_B.predict(X_test)
y_predict = np.argmax(y_predict,axis = 1)
y_predict

152/152 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


array([2, 4, 0, ..., 4, 0, 1], dtype=int64)

In [35]:
error = np.sqrt(mean_squared_error(y_test, y_predict))

In [36]:
error

0.33113172685617875

In [26]:
from keras.datasets import mnist
train, test = mnist.load_data()

In [27]:
label_index_train = train[1] > 4
label_index_test = test[1] > 4
modified_train_X = train[0][label_index_train]
modified_train_y = train[1][label_index_train]
modified_test_X = test[0][label_index_test]
modified_test_y = test[1][label_index_test]
modified_train_y = modified_train_y - 5
modified_test_y = modified_test_y - 5

In [28]:
train_X = np.concatenate((modified_train_X, modified_test_X),axis=0)
train_X.shape
train_y = np.concatenate((modified_train_y, modified_test_y),axis = 0)
train_y.shape

(34265,)

In [29]:
from sklearn.model_selection import KFold

In [30]:
import time

In [47]:
kf = KFold(n_splits = 5, shuffle = True, random_state = 42)
scores = []

In [48]:
time_list = []
index = 1
for train_index, test_index in kf.split(train_X):
    X_train, X_test = train_X[train_index],train_X[test_index]
    y_train, y_test = train_y[train_index],train_y[test_index]
    start_time = time.time()
    log_dir = f"dir/"
    tb_callback = TensorBoard(log_dir= log_dir, histogram_freq=1)
    history = model_B.fit(X_train, y_train, epochs = 16, validation_data = (X_val, y_val),callbacks = [early_stopping,tb_callback])
    end_time = time.time()
    time_list.append((end_time - start_time)*1000)
    scores.append(model_B.evaluate(X_test, y_test))

Epoch 1/16
857/857 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7044 - loss: 0.8315 - val_accuracy: 0.7378 - val_loss: 0.7575
Epoch 2/16
857/857 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7106 - loss: 0.8155 - val_accuracy: 0.7355 - val_loss: 0.7542
Epoch 3/16
857/857 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7081 - loss: 0.8165 - val_accuracy: 0.7202 - val_loss: 0.7770
Epoch 4/16
857/857 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7043 - loss: 0.8340 - val_accuracy: 0.7062 - val_loss: 0.8036
Epoch 5/16
857/857 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7037 - loss: 0.8252 - val_accuracy: 0.7321 - val_loss: 0.7652
215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.7154 - loss: 0.8356
Epoch 1/16
857/857 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7018 - loss: 0.8395 - val_accuracy: 0.7317 - val_loss: 0.7678
Epoch 2/16
857/857 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7110 - loss: 0.8193 - val_accuracy: 0.7280 - val_loss: 0.7637
Epoch 3/16
857/857 ━━━━━━━━

In [43]:
scores = np.array(scores)

In [44]:
np.mean(scores[:,1])

0.7049467206001282

In [45]:
np.mean(scores[:,0])*100

83.20311307907104

In [2]:
arr = np.arange(10)
np.save('some_array', arr)

In [3]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
X = np.random.randn(5,5)

In [5]:
np.linalg.inv(X)

array([[ -0.74239462,  -1.09650039,  -4.06803941,   5.19965956,
         -1.05884634],
       [  0.99125599,   2.23219795,   7.92238275, -11.33632488,
          2.82461797],
       [  0.16246859,   1.44362002,   6.95823026,  -9.21578968,
          1.51329479],
       [  1.27597643,   2.33282977,   7.91934464, -11.09015783,
          2.01219245],
       [  0.54795355,   0.78109261,   5.20178714,  -7.60728418,
          1.78154568]])

In [6]:
np.linalg.diag(X)

AttributeError: module 'numpy.linalg' has no attribute 'diag'

In [7]:
X.diagonal()

array([-1.10320192,  0.88509218,  0.46367349, -0.99730863, -0.0591739 ])

In [11]:
samples = np.random.normal(size = (5,5))

In [12]:
samples

array([[-0.11514115, -0.46351601,  0.47055883,  0.54558586,  0.53482725],
       [-0.53630914,  1.12632186,  0.18057147,  1.39021811, -0.69130428],
       [-0.51711882, -1.24417234, -0.09504214, -0.15892563, -0.55311206],
       [ 0.28140929,  0.9262954 , -0.69541724,  1.27853803,  1.17159303],
       [-0.33069468, -1.3830122 , -0.8553519 ,  0.54611763,  0.24698399]])

In [17]:
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: E:/conda/envs/Shakshor/Library/include
    lib directory: E:/conda/envs/Shakshor/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1868282989520
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
    cpu: x86_

In [18]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [34]:
arr = np.random.randn(5,5)
arr = np.

TypeError: only length-1 arrays can be converted to Python scalars

In [22]:
np.any(arr,0)

array([ True,  True,  True,  True,  True])

In [36]:
array = np.array([1,2,np.inf, np.nan])

In [38]:
np.all(np.isnan(array))

False

In [42]:
complex_arr = np.array([1+2j, 2+3j])

In [44]:
np.isscalar(complex_arr)

False

In [45]:
np.info(np.equal)

equal(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Return (x1 == x2) element-wise.

Parameters
----------
x1, x2 : array_like
    Input arrays.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=Non

In [46]:
array1 = np.random.rand(2,2)
array2 = np.random.rand(2,2)
np.allclose(array1, array2)

False

In [49]:
array1 = [1,2]
array2 = [1.000001,2.00001]
np.allclose(array1, array2)

True

In [50]:
array1 = np.random.randn(5,5)
array2 = np.random.randn(5,5)
np.greater(array1, array2)

array([[ True, False,  True, False,  True],
       [ True,  True,  True,  True, False],
       [False, False,  True,  True, False],
       [False, False,  True,  True,  True],
       [False, False, False,  True, False]])

In [51]:
arr = np.array([1,7,13,105])

In [55]:
size(arr.dtype)

NameError: name 'size' is not defined

In [56]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [58]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [62]:
arr = np.ones(10)
arr = arr*5
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [60]:
arr = np.ones(10)*5